import { GameState, CoinColor } from "../entity/GameType"

export const state: GameState = {
    board: [
        [
            { coin_color: CoinColor.BLUE, node: null },
            { coin_color: CoinColor.BLUE, node: null },
            { coin_color: CoinColor.BLUE, node: null },
            { coin_color: CoinColor.BLUE, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
        ],
        [
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
        ],
        [
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
        ],
        [
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
        ],
        [
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
        ],
        [
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
            { coin_color: CoinColor.BLANK, node: null },
        ],
    ],
    player: null,
    waitingPlayer: null,
    turn_is: CoinColor.RED,
}
