import { GameState, CoinColor } from "../entity/GameType"

export const state: GameState = {
    winner: null,
    board: [
        [
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
        ],
        [
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
        ],
        [
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
        ],
        [
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
        ],
        [
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
        ],
        [
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
            CoinColor.BLANK,
        ],
    ],
    player: null,
    waitingPlayer: null,
}
